global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using NetSpeed.Evolution.Core.Application.Interfaces;
global using NetSpeed.Evolution.Core.Application.ProfileMappings;
global using NetSpeed.Evolution.Core.Application.Services;
global using NetSpeed.Evolution.Core.Domain.Interfaces;
global using NetSpeed.Evolution.Infrastructure.Persistence.Contexts;
global using NetSpeed.Evolution.Infrastructure.Persistence.Repositories;
