use NetSpeedEvolution
go

insert into Department([name])
values
 ('Administrativo')
, ('Comercial')
, ('Desenvolvimento')
, ('Financeiro')
, ('Fiscal-Contábil')
, ('Folha de Pagamento')
, ('Infraestrutura')
, ('Portal Educação')
, ('RH')
, ('TI interna')
go

insert into HardSkill ([Name])
values
('Amazon Web Services (AWS)'),
('Android'),
('Angular'),
('Apache Kafka'),
('Apache Spark'),
('Arduino'),
('ASP.NET Core'),
('AutoMapper'),
('Azure DevOps'),
('Azure Functions'),
('Azure SQL Database'),
('Bootstrap'),
('C'),
('C#'),
('C++'),
('CSS'),
('Dart'),
('DataTables.js'),
('Docker'),
('Elasticsearch'),
('Entity Framework Core'),
('Express.js'),
('Firebase'),
('Flask'),
('FluentValidation'),
('Flutter'),
('Git'),
('GitHub'),
('GitLab'),
('Go'),
('Google Cloud Platform (GCP)'),
('GraphQL'),
('gRPC'),
('Hibernate'),
('HTML'),
('IntelliJ IDEA'),
('Ionic'),
('Java'),
('JavaScript'),
('Jenkins'),
('Jest'),
('JIRA'),
('JQuery'),
('Julia'),
('Kotlin'),
('Kubernetes'),
('Laravel'),
('Linux'),
('MAUI'),
('MariaDB'),
('Microsoft Azure'),
('MongoDB'),
('MS SQL Server'),
('MySQL'),
('NestJS'),
('Next.js'),
('Node.js'),
('NoSQL'),
('NumPy'),
('OpenAI API'),
('OpenXML'),
('Oracle Database'),
('PHP'),
('PostgreSQL'),
('Power BI'),
('Python'),
('PyTorch'),
('Qt'),
('R'),
('RabbitMQ'),
('React'),
('Redis'),
('REST API'),
('Rust'),
('Scala'),
('Spring Boot'),
('SQLite'),
('Swagger'),
('Swift'),
('TensorFlow'),
('Terraform'),
('TypeScript'),
('Unity'),
('Unreal Engine'),
('Visual Studio'),
('Visual Studio Code'),
('Vue.js'),
('Windows Forms'),
('XAML'),
('XML');
go
